// PrivyQ core gRPC contract.
//
// This is the single, frozen interface between the Python SDK (and any future
// language SDK) and the Go cryptographic core. It is derived from
// docs/SYSTEM_ARCHITECTURE.md §7.3 & §8.1 and docs/blueprint.md Appendix A/B.
//
// Regenerate stubs with `make proto` (see repo root Makefile).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: privyq.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PrivyQCore_GenerateKey_FullMethodName      = "/privyq.v1.PrivyQCore/GenerateKey"
	PrivyQCore_RotateKey_FullMethodName        = "/privyq.v1.PrivyQCore/RotateKey"
	PrivyQCore_RevokeKey_FullMethodName        = "/privyq.v1.PrivyQCore/RevokeKey"
	PrivyQCore_GetPublicKey_FullMethodName     = "/privyq.v1.PrivyQCore/GetPublicKey"
	PrivyQCore_ListKeys_FullMethodName         = "/privyq.v1.PrivyQCore/ListKeys"
	PrivyQCore_EvaluatePolicy_FullMethodName   = "/privyq.v1.PrivyQCore/EvaluatePolicy"
	PrivyQCore_Check_FullMethodName            = "/privyq.v1.PrivyQCore/Check"
	PrivyQCore_Protect_FullMethodName          = "/privyq.v1.PrivyQCore/Protect"
	PrivyQCore_Access_FullMethodName           = "/privyq.v1.PrivyQCore/Access"
	PrivyQCore_Sign_FullMethodName             = "/privyq.v1.PrivyQCore/Sign"
	PrivyQCore_Verify_FullMethodName           = "/privyq.v1.PrivyQCore/Verify"
	PrivyQCore_Seal_FullMethodName             = "/privyq.v1.PrivyQCore/Seal"
	PrivyQCore_VerifySeal_FullMethodName       = "/privyq.v1.PrivyQCore/VerifySeal"
	PrivyQCore_GenerateEvidence_FullMethodName = "/privyq.v1.PrivyQCore/GenerateEvidence"
	PrivyQCore_VerifyEvidence_FullMethodName   = "/privyq.v1.PrivyQCore/VerifyEvidence"
	PrivyQCore_GetEvidenceLog_FullMethodName   = "/privyq.v1.PrivyQCore/GetEvidenceLog"
	PrivyQCore_ExportEvidence_FullMethodName   = "/privyq.v1.PrivyQCore/ExportEvidence"
	PrivyQCore_ComplianceReport_FullMethodName = "/privyq.v1.PrivyQCore/ComplianceReport"
	PrivyQCore_VerifyWallet_FullMethodName     = "/privyq.v1.PrivyQCore/VerifyWallet"
	PrivyQCore_Health_FullMethodName           = "/privyq.v1.PrivyQCore/Health"
)

// PrivyQCoreClient is the client API for PrivyQCore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrivyQCoreClient interface {
	// Key management
	GenerateKey(ctx context.Context, in *GenerateKeyRequest, opts ...grpc.CallOption) (*GenerateKeyResponse, error)
	RotateKey(ctx context.Context, in *RotateKeyRequest, opts ...grpc.CallOption) (*RotateKeyResponse, error)
	RevokeKey(ctx context.Context, in *RevokeKeyRequest, opts ...grpc.CallOption) (*RevokeKeyResponse, error)
	GetPublicKey(ctx context.Context, in *GetPublicKeyRequest, opts ...grpc.CallOption) (*GetPublicKeyResponse, error)
	ListKeys(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*ListKeysResponse, error)
	// Policy evaluation (no side effects — used by the playground)
	EvaluatePolicy(ctx context.Context, in *EvaluatePolicyRequest, opts ...grpc.CallOption) (*EvaluatePolicyResponse, error)
	// Authorization decision (PDP) — the v2 `check()` verb, no data revealed
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
	// Encryption / decryption
	Protect(ctx context.Context, in *ProtectRequest, opts ...grpc.CallOption) (*ProtectResponse, error)
	Access(ctx context.Context, in *AccessRequest, opts ...grpc.CallOption) (*AccessResponse, error)
	// Signatures
	Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error)
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
	Seal(ctx context.Context, in *SealRequest, opts ...grpc.CallOption) (*SealResponse, error)
	VerifySeal(ctx context.Context, in *VerifySealRequest, opts ...grpc.CallOption) (*VerifySealResponse, error)
	// Audit
	GenerateEvidence(ctx context.Context, in *GenerateEvidenceRequest, opts ...grpc.CallOption) (*GenerateEvidenceResponse, error)
	VerifyEvidence(ctx context.Context, in *VerifyEvidenceRequest, opts ...grpc.CallOption) (*VerifyEvidenceResponse, error)
	GetEvidenceLog(ctx context.Context, in *GetEvidenceLogRequest, opts ...grpc.CallOption) (*GetEvidenceLogResponse, error)
	ExportEvidence(ctx context.Context, in *ExportEvidenceRequest, opts ...grpc.CallOption) (*ExportEvidenceResponse, error)
	ComplianceReport(ctx context.Context, in *ComplianceReportRequest, opts ...grpc.CallOption) (*ComplianceReportResponse, error)
	VerifyWallet(ctx context.Context, in *VerifyWalletRequest, opts ...grpc.CallOption) (*VerifyWalletResponse, error)
	// Ops
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type privyQCoreClient struct {
	cc grpc.ClientConnInterface
}

func NewPrivyQCoreClient(cc grpc.ClientConnInterface) PrivyQCoreClient {
	return &privyQCoreClient{cc}
}

func (c *privyQCoreClient) GenerateKey(ctx context.Context, in *GenerateKeyRequest, opts ...grpc.CallOption) (*GenerateKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateKeyResponse)
	err := c.cc.Invoke(ctx, PrivyQCore_GenerateKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privyQCoreClient) RotateKey(ctx context.Context, in *RotateKeyRequest, opts ...grpc.CallOption) (*RotateKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateKeyResponse)
	err := c.cc.Invoke(ctx, PrivyQCore_RotateKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privyQCoreClient) RevokeKey(ctx context.Context, in *RevokeKeyRequest, opts ...grpc.CallOption) (*RevokeKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeKeyResponse)
	err := c.cc.Invoke(ctx, PrivyQCore_RevokeKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privyQCoreClient) GetPublicKey(ctx context.Context, in *GetPublicKeyRequest, opts ...grpc.CallOption) (*GetPublicKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublicKeyResponse)
	err := c.cc.Invoke(ctx, PrivyQCore_GetPublicKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privyQCoreClient) ListKeys(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*ListKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListKeysResponse)
	err := c.cc.Invoke(ctx, PrivyQCore_ListKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privyQCoreClient) EvaluatePolicy(ctx context.Context, in *EvaluatePolicyRequest, opts ...grpc.CallOption) (*EvaluatePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluatePolicyResponse)
	err := c.cc.Invoke(ctx, PrivyQCore_EvaluatePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privyQCoreClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, PrivyQCore_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privyQCoreClient) Protect(ctx context.Context, in *ProtectRequest, opts ...grpc.CallOption) (*ProtectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProtectResponse)
	err := c.cc.Invoke(ctx, PrivyQCore_Protect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privyQCoreClient) Access(ctx context.Context, in *AccessRequest, opts ...grpc.CallOption) (*AccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessResponse)
	err := c.cc.Invoke(ctx, PrivyQCore_Access_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privyQCoreClient) Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignResponse)
	err := c.cc.Invoke(ctx, PrivyQCore_Sign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privyQCoreClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, PrivyQCore_Verify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privyQCoreClient) Seal(ctx context.Context, in *SealRequest, opts ...grpc.CallOption) (*SealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SealResponse)
	err := c.cc.Invoke(ctx, PrivyQCore_Seal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privyQCoreClient) VerifySeal(ctx context.Context, in *VerifySealRequest, opts ...grpc.CallOption) (*VerifySealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifySealResponse)
	err := c.cc.Invoke(ctx, PrivyQCore_VerifySeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privyQCoreClient) GenerateEvidence(ctx context.Context, in *GenerateEvidenceRequest, opts ...grpc.CallOption) (*GenerateEvidenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateEvidenceResponse)
	err := c.cc.Invoke(ctx, PrivyQCore_GenerateEvidence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privyQCoreClient) VerifyEvidence(ctx context.Context, in *VerifyEvidenceRequest, opts ...grpc.CallOption) (*VerifyEvidenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyEvidenceResponse)
	err := c.cc.Invoke(ctx, PrivyQCore_VerifyEvidence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privyQCoreClient) GetEvidenceLog(ctx context.Context, in *GetEvidenceLogRequest, opts ...grpc.CallOption) (*GetEvidenceLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEvidenceLogResponse)
	err := c.cc.Invoke(ctx, PrivyQCore_GetEvidenceLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privyQCoreClient) ExportEvidence(ctx context.Context, in *ExportEvidenceRequest, opts ...grpc.CallOption) (*ExportEvidenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportEvidenceResponse)
	err := c.cc.Invoke(ctx, PrivyQCore_ExportEvidence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privyQCoreClient) ComplianceReport(ctx context.Context, in *ComplianceReportRequest, opts ...grpc.CallOption) (*ComplianceReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComplianceReportResponse)
	err := c.cc.Invoke(ctx, PrivyQCore_ComplianceReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privyQCoreClient) VerifyWallet(ctx context.Context, in *VerifyWalletRequest, opts ...grpc.CallOption) (*VerifyWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyWalletResponse)
	err := c.cc.Invoke(ctx, PrivyQCore_VerifyWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *privyQCoreClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, PrivyQCore_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrivyQCoreServer is the server API for PrivyQCore service.
// All implementations must embed UnimplementedPrivyQCoreServer
// for forward compatibility.
type PrivyQCoreServer interface {
	// Key management
	GenerateKey(context.Context, *GenerateKeyRequest) (*GenerateKeyResponse, error)
	RotateKey(context.Context, *RotateKeyRequest) (*RotateKeyResponse, error)
	RevokeKey(context.Context, *RevokeKeyRequest) (*RevokeKeyResponse, error)
	GetPublicKey(context.Context, *GetPublicKeyRequest) (*GetPublicKeyResponse, error)
	ListKeys(context.Context, *ListKeysRequest) (*ListKeysResponse, error)
	// Policy evaluation (no side effects — used by the playground)
	EvaluatePolicy(context.Context, *EvaluatePolicyRequest) (*EvaluatePolicyResponse, error)
	// Authorization decision (PDP) — the v2 `check()` verb, no data revealed
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
	// Encryption / decryption
	Protect(context.Context, *ProtectRequest) (*ProtectResponse, error)
	Access(context.Context, *AccessRequest) (*AccessResponse, error)
	// Signatures
	Sign(context.Context, *SignRequest) (*SignResponse, error)
	Verify(context.Context, *VerifyRequest) (*VerifyResponse, error)
	Seal(context.Context, *SealRequest) (*SealResponse, error)
	VerifySeal(context.Context, *VerifySealRequest) (*VerifySealResponse, error)
	// Audit
	GenerateEvidence(context.Context, *GenerateEvidenceRequest) (*GenerateEvidenceResponse, error)
	VerifyEvidence(context.Context, *VerifyEvidenceRequest) (*VerifyEvidenceResponse, error)
	GetEvidenceLog(context.Context, *GetEvidenceLogRequest) (*GetEvidenceLogResponse, error)
	ExportEvidence(context.Context, *ExportEvidenceRequest) (*ExportEvidenceResponse, error)
	ComplianceReport(context.Context, *ComplianceReportRequest) (*ComplianceReportResponse, error)
	VerifyWallet(context.Context, *VerifyWalletRequest) (*VerifyWalletResponse, error)
	// Ops
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedPrivyQCoreServer()
}

// UnimplementedPrivyQCoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrivyQCoreServer struct{}

func (UnimplementedPrivyQCoreServer) GenerateKey(context.Context, *GenerateKeyRequest) (*GenerateKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateKey not implemented")
}
func (UnimplementedPrivyQCoreServer) RotateKey(context.Context, *RotateKeyRequest) (*RotateKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RotateKey not implemented")
}
func (UnimplementedPrivyQCoreServer) RevokeKey(context.Context, *RevokeKeyRequest) (*RevokeKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeKey not implemented")
}
func (UnimplementedPrivyQCoreServer) GetPublicKey(context.Context, *GetPublicKeyRequest) (*GetPublicKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublicKey not implemented")
}
func (UnimplementedPrivyQCoreServer) ListKeys(context.Context, *ListKeysRequest) (*ListKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListKeys not implemented")
}
func (UnimplementedPrivyQCoreServer) EvaluatePolicy(context.Context, *EvaluatePolicyRequest) (*EvaluatePolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluatePolicy not implemented")
}
func (UnimplementedPrivyQCoreServer) Check(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedPrivyQCoreServer) Protect(context.Context, *ProtectRequest) (*ProtectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Protect not implemented")
}
func (UnimplementedPrivyQCoreServer) Access(context.Context, *AccessRequest) (*AccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Access not implemented")
}
func (UnimplementedPrivyQCoreServer) Sign(context.Context, *SignRequest) (*SignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sign not implemented")
}
func (UnimplementedPrivyQCoreServer) Verify(context.Context, *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedPrivyQCoreServer) Seal(context.Context, *SealRequest) (*SealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Seal not implemented")
}
func (UnimplementedPrivyQCoreServer) VerifySeal(context.Context, *VerifySealRequest) (*VerifySealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifySeal not implemented")
}
func (UnimplementedPrivyQCoreServer) GenerateEvidence(context.Context, *GenerateEvidenceRequest) (*GenerateEvidenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateEvidence not implemented")
}
func (UnimplementedPrivyQCoreServer) VerifyEvidence(context.Context, *VerifyEvidenceRequest) (*VerifyEvidenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyEvidence not implemented")
}
func (UnimplementedPrivyQCoreServer) GetEvidenceLog(context.Context, *GetEvidenceLogRequest) (*GetEvidenceLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvidenceLog not implemented")
}
func (UnimplementedPrivyQCoreServer) ExportEvidence(context.Context, *ExportEvidenceRequest) (*ExportEvidenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportEvidence not implemented")
}
func (UnimplementedPrivyQCoreServer) ComplianceReport(context.Context, *ComplianceReportRequest) (*ComplianceReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ComplianceReport not implemented")
}
func (UnimplementedPrivyQCoreServer) VerifyWallet(context.Context, *VerifyWalletRequest) (*VerifyWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyWallet not implemented")
}
func (UnimplementedPrivyQCoreServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedPrivyQCoreServer) mustEmbedUnimplementedPrivyQCoreServer() {}
func (UnimplementedPrivyQCoreServer) testEmbeddedByValue()                    {}

// UnsafePrivyQCoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrivyQCoreServer will
// result in compilation errors.
type UnsafePrivyQCoreServer interface {
	mustEmbedUnimplementedPrivyQCoreServer()
}

func RegisterPrivyQCoreServer(s grpc.ServiceRegistrar, srv PrivyQCoreServer) {
	// If the following call pancis, it indicates UnimplementedPrivyQCoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PrivyQCore_ServiceDesc, srv)
}

func _PrivyQCore_GenerateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivyQCoreServer).GenerateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivyQCore_GenerateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivyQCoreServer).GenerateKey(ctx, req.(*GenerateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivyQCore_RotateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivyQCoreServer).RotateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivyQCore_RotateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivyQCoreServer).RotateKey(ctx, req.(*RotateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivyQCore_RevokeKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivyQCoreServer).RevokeKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivyQCore_RevokeKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivyQCoreServer).RevokeKey(ctx, req.(*RevokeKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivyQCore_GetPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivyQCoreServer).GetPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivyQCore_GetPublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivyQCoreServer).GetPublicKey(ctx, req.(*GetPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivyQCore_ListKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivyQCoreServer).ListKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivyQCore_ListKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivyQCoreServer).ListKeys(ctx, req.(*ListKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivyQCore_EvaluatePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluatePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivyQCoreServer).EvaluatePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivyQCore_EvaluatePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivyQCoreServer).EvaluatePolicy(ctx, req.(*EvaluatePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivyQCore_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivyQCoreServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivyQCore_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivyQCoreServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivyQCore_Protect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivyQCoreServer).Protect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivyQCore_Protect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivyQCoreServer).Protect(ctx, req.(*ProtectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivyQCore_Access_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivyQCoreServer).Access(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivyQCore_Access_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivyQCoreServer).Access(ctx, req.(*AccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivyQCore_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivyQCoreServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivyQCore_Sign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivyQCoreServer).Sign(ctx, req.(*SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivyQCore_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivyQCoreServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivyQCore_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivyQCoreServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivyQCore_Seal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivyQCoreServer).Seal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivyQCore_Seal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivyQCoreServer).Seal(ctx, req.(*SealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivyQCore_VerifySeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivyQCoreServer).VerifySeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivyQCore_VerifySeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivyQCoreServer).VerifySeal(ctx, req.(*VerifySealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivyQCore_GenerateEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateEvidenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivyQCoreServer).GenerateEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivyQCore_GenerateEvidence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivyQCoreServer).GenerateEvidence(ctx, req.(*GenerateEvidenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivyQCore_VerifyEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyEvidenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivyQCoreServer).VerifyEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivyQCore_VerifyEvidence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivyQCoreServer).VerifyEvidence(ctx, req.(*VerifyEvidenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivyQCore_GetEvidenceLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEvidenceLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivyQCoreServer).GetEvidenceLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivyQCore_GetEvidenceLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivyQCoreServer).GetEvidenceLog(ctx, req.(*GetEvidenceLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivyQCore_ExportEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportEvidenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivyQCoreServer).ExportEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivyQCore_ExportEvidence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivyQCoreServer).ExportEvidence(ctx, req.(*ExportEvidenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivyQCore_ComplianceReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComplianceReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivyQCoreServer).ComplianceReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivyQCore_ComplianceReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivyQCoreServer).ComplianceReport(ctx, req.(*ComplianceReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivyQCore_VerifyWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivyQCoreServer).VerifyWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivyQCore_VerifyWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivyQCoreServer).VerifyWallet(ctx, req.(*VerifyWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrivyQCore_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrivyQCoreServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrivyQCore_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrivyQCoreServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PrivyQCore_ServiceDesc is the grpc.ServiceDesc for PrivyQCore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrivyQCore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "privyq.v1.PrivyQCore",
	HandlerType: (*PrivyQCoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateKey",
			Handler:    _PrivyQCore_GenerateKey_Handler,
		},
		{
			MethodName: "RotateKey",
			Handler:    _PrivyQCore_RotateKey_Handler,
		},
		{
			MethodName: "RevokeKey",
			Handler:    _PrivyQCore_RevokeKey_Handler,
		},
		{
			MethodName: "GetPublicKey",
			Handler:    _PrivyQCore_GetPublicKey_Handler,
		},
		{
			MethodName: "ListKeys",
			Handler:    _PrivyQCore_ListKeys_Handler,
		},
		{
			MethodName: "EvaluatePolicy",
			Handler:    _PrivyQCore_EvaluatePolicy_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _PrivyQCore_Check_Handler,
		},
		{
			MethodName: "Protect",
			Handler:    _PrivyQCore_Protect_Handler,
		},
		{
			MethodName: "Access",
			Handler:    _PrivyQCore_Access_Handler,
		},
		{
			MethodName: "Sign",
			Handler:    _PrivyQCore_Sign_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _PrivyQCore_Verify_Handler,
		},
		{
			MethodName: "Seal",
			Handler:    _PrivyQCore_Seal_Handler,
		},
		{
			MethodName: "VerifySeal",
			Handler:    _PrivyQCore_VerifySeal_Handler,
		},
		{
			MethodName: "GenerateEvidence",
			Handler:    _PrivyQCore_GenerateEvidence_Handler,
		},
		{
			MethodName: "VerifyEvidence",
			Handler:    _PrivyQCore_VerifyEvidence_Handler,
		},
		{
			MethodName: "GetEvidenceLog",
			Handler:    _PrivyQCore_GetEvidenceLog_Handler,
		},
		{
			MethodName: "ExportEvidence",
			Handler:    _PrivyQCore_ExportEvidence_Handler,
		},
		{
			MethodName: "ComplianceReport",
			Handler:    _PrivyQCore_ComplianceReport_Handler,
		},
		{
			MethodName: "VerifyWallet",
			Handler:    _PrivyQCore_VerifyWallet_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _PrivyQCore_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "privyq.proto",
}
