# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import privyq_pb2 as privyq__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in privyq_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PrivyQCoreStub:
    """─────────────────────────────────────────────────────────────────────────────
    Service (docs/SYSTEM_ARCHITECTURE.md §7.3)
    ─────────────────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateKey = channel.unary_unary(
                '/privyq.v1.PrivyQCore/GenerateKey',
                request_serializer=privyq__pb2.GenerateKeyRequest.SerializeToString,
                response_deserializer=privyq__pb2.GenerateKeyResponse.FromString,
                _registered_method=True)
        self.RotateKey = channel.unary_unary(
                '/privyq.v1.PrivyQCore/RotateKey',
                request_serializer=privyq__pb2.RotateKeyRequest.SerializeToString,
                response_deserializer=privyq__pb2.RotateKeyResponse.FromString,
                _registered_method=True)
        self.RevokeKey = channel.unary_unary(
                '/privyq.v1.PrivyQCore/RevokeKey',
                request_serializer=privyq__pb2.RevokeKeyRequest.SerializeToString,
                response_deserializer=privyq__pb2.RevokeKeyResponse.FromString,
                _registered_method=True)
        self.GetPublicKey = channel.unary_unary(
                '/privyq.v1.PrivyQCore/GetPublicKey',
                request_serializer=privyq__pb2.GetPublicKeyRequest.SerializeToString,
                response_deserializer=privyq__pb2.GetPublicKeyResponse.FromString,
                _registered_method=True)
        self.ListKeys = channel.unary_unary(
                '/privyq.v1.PrivyQCore/ListKeys',
                request_serializer=privyq__pb2.ListKeysRequest.SerializeToString,
                response_deserializer=privyq__pb2.ListKeysResponse.FromString,
                _registered_method=True)
        self.EvaluatePolicy = channel.unary_unary(
                '/privyq.v1.PrivyQCore/EvaluatePolicy',
                request_serializer=privyq__pb2.EvaluatePolicyRequest.SerializeToString,
                response_deserializer=privyq__pb2.EvaluatePolicyResponse.FromString,
                _registered_method=True)
        self.Check = channel.unary_unary(
                '/privyq.v1.PrivyQCore/Check',
                request_serializer=privyq__pb2.CheckRequest.SerializeToString,
                response_deserializer=privyq__pb2.CheckResponse.FromString,
                _registered_method=True)
        self.Protect = channel.unary_unary(
                '/privyq.v1.PrivyQCore/Protect',
                request_serializer=privyq__pb2.ProtectRequest.SerializeToString,
                response_deserializer=privyq__pb2.ProtectResponse.FromString,
                _registered_method=True)
        self.Access = channel.unary_unary(
                '/privyq.v1.PrivyQCore/Access',
                request_serializer=privyq__pb2.AccessRequest.SerializeToString,
                response_deserializer=privyq__pb2.AccessResponse.FromString,
                _registered_method=True)
        self.Sign = channel.unary_unary(
                '/privyq.v1.PrivyQCore/Sign',
                request_serializer=privyq__pb2.SignRequest.SerializeToString,
                response_deserializer=privyq__pb2.SignResponse.FromString,
                _registered_method=True)
        self.Verify = channel.unary_unary(
                '/privyq.v1.PrivyQCore/Verify',
                request_serializer=privyq__pb2.VerifyRequest.SerializeToString,
                response_deserializer=privyq__pb2.VerifyResponse.FromString,
                _registered_method=True)
        self.Seal = channel.unary_unary(
                '/privyq.v1.PrivyQCore/Seal',
                request_serializer=privyq__pb2.SealRequest.SerializeToString,
                response_deserializer=privyq__pb2.SealResponse.FromString,
                _registered_method=True)
        self.VerifySeal = channel.unary_unary(
                '/privyq.v1.PrivyQCore/VerifySeal',
                request_serializer=privyq__pb2.VerifySealRequest.SerializeToString,
                response_deserializer=privyq__pb2.VerifySealResponse.FromString,
                _registered_method=True)
        self.GenerateEvidence = channel.unary_unary(
                '/privyq.v1.PrivyQCore/GenerateEvidence',
                request_serializer=privyq__pb2.GenerateEvidenceRequest.SerializeToString,
                response_deserializer=privyq__pb2.GenerateEvidenceResponse.FromString,
                _registered_method=True)
        self.VerifyEvidence = channel.unary_unary(
                '/privyq.v1.PrivyQCore/VerifyEvidence',
                request_serializer=privyq__pb2.VerifyEvidenceRequest.SerializeToString,
                response_deserializer=privyq__pb2.VerifyEvidenceResponse.FromString,
                _registered_method=True)
        self.GetEvidenceLog = channel.unary_unary(
                '/privyq.v1.PrivyQCore/GetEvidenceLog',
                request_serializer=privyq__pb2.GetEvidenceLogRequest.SerializeToString,
                response_deserializer=privyq__pb2.GetEvidenceLogResponse.FromString,
                _registered_method=True)
        self.ExportEvidence = channel.unary_unary(
                '/privyq.v1.PrivyQCore/ExportEvidence',
                request_serializer=privyq__pb2.ExportEvidenceRequest.SerializeToString,
                response_deserializer=privyq__pb2.ExportEvidenceResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/privyq.v1.PrivyQCore/Health',
                request_serializer=privyq__pb2.HealthRequest.SerializeToString,
                response_deserializer=privyq__pb2.HealthResponse.FromString,
                _registered_method=True)


class PrivyQCoreServicer:
    """─────────────────────────────────────────────────────────────────────────────
    Service (docs/SYSTEM_ARCHITECTURE.md §7.3)
    ─────────────────────────────────────────────────────────────────────────────

    """

    def GenerateKey(self, request, context):
        """Key management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RotateKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPublicKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluatePolicy(self, request, context):
        """Policy evaluation (no side effects — used by the playground)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Check(self, request, context):
        """Authorization decision (PDP) — the v2 `check()` verb, no data revealed
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Protect(self, request, context):
        """Encryption / decryption
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Access(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sign(self, request, context):
        """Signatures
        low-level
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Verify(self, request, context):
        """low-level
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Seal(self, request, context):
        """v2 `seal()` — self-describing Sealed
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifySeal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateEvidence(self, request, context):
        """Audit
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyEvidence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvidenceLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportEvidence(self, request, context):
        """v2 compliance export
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Ops
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrivyQCoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateKey,
                    request_deserializer=privyq__pb2.GenerateKeyRequest.FromString,
                    response_serializer=privyq__pb2.GenerateKeyResponse.SerializeToString,
            ),
            'RotateKey': grpc.unary_unary_rpc_method_handler(
                    servicer.RotateKey,
                    request_deserializer=privyq__pb2.RotateKeyRequest.FromString,
                    response_serializer=privyq__pb2.RotateKeyResponse.SerializeToString,
            ),
            'RevokeKey': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeKey,
                    request_deserializer=privyq__pb2.RevokeKeyRequest.FromString,
                    response_serializer=privyq__pb2.RevokeKeyResponse.SerializeToString,
            ),
            'GetPublicKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPublicKey,
                    request_deserializer=privyq__pb2.GetPublicKeyRequest.FromString,
                    response_serializer=privyq__pb2.GetPublicKeyResponse.SerializeToString,
            ),
            'ListKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.ListKeys,
                    request_deserializer=privyq__pb2.ListKeysRequest.FromString,
                    response_serializer=privyq__pb2.ListKeysResponse.SerializeToString,
            ),
            'EvaluatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluatePolicy,
                    request_deserializer=privyq__pb2.EvaluatePolicyRequest.FromString,
                    response_serializer=privyq__pb2.EvaluatePolicyResponse.SerializeToString,
            ),
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=privyq__pb2.CheckRequest.FromString,
                    response_serializer=privyq__pb2.CheckResponse.SerializeToString,
            ),
            'Protect': grpc.unary_unary_rpc_method_handler(
                    servicer.Protect,
                    request_deserializer=privyq__pb2.ProtectRequest.FromString,
                    response_serializer=privyq__pb2.ProtectResponse.SerializeToString,
            ),
            'Access': grpc.unary_unary_rpc_method_handler(
                    servicer.Access,
                    request_deserializer=privyq__pb2.AccessRequest.FromString,
                    response_serializer=privyq__pb2.AccessResponse.SerializeToString,
            ),
            'Sign': grpc.unary_unary_rpc_method_handler(
                    servicer.Sign,
                    request_deserializer=privyq__pb2.SignRequest.FromString,
                    response_serializer=privyq__pb2.SignResponse.SerializeToString,
            ),
            'Verify': grpc.unary_unary_rpc_method_handler(
                    servicer.Verify,
                    request_deserializer=privyq__pb2.VerifyRequest.FromString,
                    response_serializer=privyq__pb2.VerifyResponse.SerializeToString,
            ),
            'Seal': grpc.unary_unary_rpc_method_handler(
                    servicer.Seal,
                    request_deserializer=privyq__pb2.SealRequest.FromString,
                    response_serializer=privyq__pb2.SealResponse.SerializeToString,
            ),
            'VerifySeal': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifySeal,
                    request_deserializer=privyq__pb2.VerifySealRequest.FromString,
                    response_serializer=privyq__pb2.VerifySealResponse.SerializeToString,
            ),
            'GenerateEvidence': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateEvidence,
                    request_deserializer=privyq__pb2.GenerateEvidenceRequest.FromString,
                    response_serializer=privyq__pb2.GenerateEvidenceResponse.SerializeToString,
            ),
            'VerifyEvidence': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyEvidence,
                    request_deserializer=privyq__pb2.VerifyEvidenceRequest.FromString,
                    response_serializer=privyq__pb2.VerifyEvidenceResponse.SerializeToString,
            ),
            'GetEvidenceLog': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvidenceLog,
                    request_deserializer=privyq__pb2.GetEvidenceLogRequest.FromString,
                    response_serializer=privyq__pb2.GetEvidenceLogResponse.SerializeToString,
            ),
            'ExportEvidence': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportEvidence,
                    request_deserializer=privyq__pb2.ExportEvidenceRequest.FromString,
                    response_serializer=privyq__pb2.ExportEvidenceResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=privyq__pb2.HealthRequest.FromString,
                    response_serializer=privyq__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'privyq.v1.PrivyQCore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('privyq.v1.PrivyQCore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PrivyQCore:
    """─────────────────────────────────────────────────────────────────────────────
    Service (docs/SYSTEM_ARCHITECTURE.md §7.3)
    ─────────────────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def GenerateKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privyq.v1.PrivyQCore/GenerateKey',
            privyq__pb2.GenerateKeyRequest.SerializeToString,
            privyq__pb2.GenerateKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RotateKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privyq.v1.PrivyQCore/RotateKey',
            privyq__pb2.RotateKeyRequest.SerializeToString,
            privyq__pb2.RotateKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privyq.v1.PrivyQCore/RevokeKey',
            privyq__pb2.RevokeKeyRequest.SerializeToString,
            privyq__pb2.RevokeKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPublicKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privyq.v1.PrivyQCore/GetPublicKey',
            privyq__pb2.GetPublicKeyRequest.SerializeToString,
            privyq__pb2.GetPublicKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privyq.v1.PrivyQCore/ListKeys',
            privyq__pb2.ListKeysRequest.SerializeToString,
            privyq__pb2.ListKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privyq.v1.PrivyQCore/EvaluatePolicy',
            privyq__pb2.EvaluatePolicyRequest.SerializeToString,
            privyq__pb2.EvaluatePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privyq.v1.PrivyQCore/Check',
            privyq__pb2.CheckRequest.SerializeToString,
            privyq__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Protect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privyq.v1.PrivyQCore/Protect',
            privyq__pb2.ProtectRequest.SerializeToString,
            privyq__pb2.ProtectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Access(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privyq.v1.PrivyQCore/Access',
            privyq__pb2.AccessRequest.SerializeToString,
            privyq__pb2.AccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privyq.v1.PrivyQCore/Sign',
            privyq__pb2.SignRequest.SerializeToString,
            privyq__pb2.SignResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Verify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privyq.v1.PrivyQCore/Verify',
            privyq__pb2.VerifyRequest.SerializeToString,
            privyq__pb2.VerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Seal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privyq.v1.PrivyQCore/Seal',
            privyq__pb2.SealRequest.SerializeToString,
            privyq__pb2.SealResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifySeal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privyq.v1.PrivyQCore/VerifySeal',
            privyq__pb2.VerifySealRequest.SerializeToString,
            privyq__pb2.VerifySealResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateEvidence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privyq.v1.PrivyQCore/GenerateEvidence',
            privyq__pb2.GenerateEvidenceRequest.SerializeToString,
            privyq__pb2.GenerateEvidenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyEvidence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privyq.v1.PrivyQCore/VerifyEvidence',
            privyq__pb2.VerifyEvidenceRequest.SerializeToString,
            privyq__pb2.VerifyEvidenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvidenceLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privyq.v1.PrivyQCore/GetEvidenceLog',
            privyq__pb2.GetEvidenceLogRequest.SerializeToString,
            privyq__pb2.GetEvidenceLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportEvidence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privyq.v1.PrivyQCore/ExportEvidence',
            privyq__pb2.ExportEvidenceRequest.SerializeToString,
            privyq__pb2.ExportEvidenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/privyq.v1.PrivyQCore/Health',
            privyq__pb2.HealthRequest.SerializeToString,
            privyq__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
