/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/protect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Protect
         * @description Encrypt data with an embedded policy (BP App B.1).
         */
        post: operations["protect_api_v1_protect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Access
         * @description Decrypt data if the embedded policy is satisfied (BP App B.2).
         *
         *     Returns 403 with the policy evaluation when access is denied.
         */
        post: operations["access_api_v1_access_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify
         * @description Verify an audit evidence entry (BP App B.3).
         */
        post: operations["verify_api_v1_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evidence/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Evidence Log
         * @description Retrieve audit evidence for a resource/actor (BP App B.4).
         */
        get: operations["evidence_log_api_v1_evidence_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Keys
         * @description List all managed keys with their status.
         */
        get: operations["list_keys_api_v1_keys_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keys/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate
         * @description Generate a new key pair (BP App B.5).
         */
        post: operations["generate_api_v1_keys_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Key
         * @description Get public key info by id (BP App B; closes v1 gap B6).
         */
        get: operations["get_key_api_v1_keys__key_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keys/rotate/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate
         * @description Rotate a key (BP App B.6).
         */
        post: operations["rotate_api_v1_keys_rotate__key_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keys/revoke/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke
         * @description Revoke a key.
         */
        post: operations["revoke_api_v1_keys_revoke__key_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policy/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate
         * @description Evaluate a policy against an identity/context — no side effects.
         *
         *     Powers the interactive policy playground; runs the core's real policy engine.
         */
        post: operations["evaluate_api_v1_policy_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check
         * @description The PDP decision — can this identity access this? No data revealed.
         *
         *     Any service can call this to enforce the same policies consistently.
         */
        post: operations["check_api_v1_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Explain
         * @description Human-readable reason for a decision (great for 403 bodies, debugging, UX).
         */
        post: operations["explain_api_v1_explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seal
         * @description Post-quantum signature over data (the v2 seal() verb).
         */
        post: operations["seal_api_v1_seal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evidence/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Evidence
         * @description Export the evidence trail as json | csv | pdf for compliance.
         */
        get: operations["export_evidence_api_v1_evidence_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compliance/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compliance Report
         * @description Map the evidence trail onto GDPR/HIPAA/SOC2 controls.
         */
        get: operations["compliance_report_api_v1_compliance_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Service health, including core reachability (BP App B.7).
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccessRequest */
        AccessRequest: {
            /** Protected Data */
            protected_data: string;
            /** Identity */
            identity: {
                [key: string]: unknown;
            };
            /** Context */
            context?: {
                [key: string]: unknown;
            } | null;
        };
        /** AccessResponse */
        AccessResponse: {
            /**
             * Data
             * @description base64-encoded plaintext
             */
            data: string;
            audit_evidence: components["schemas"]["EvidenceModel"];
        };
        /** CheckRequest */
        CheckRequest: {
            /** Identity */
            identity: {
                [key: string]: unknown;
            };
            /** Policy */
            policy?: {
                [key: string]: unknown;
            } | null;
            /**
             * Protected Data
             * @description base64 envelope (policy taken from it)
             */
            protected_data?: string | null;
            /** Context */
            context?: {
                [key: string]: unknown;
            } | null;
            /**
             * Emit Evidence
             * @default false
             */
            emit_evidence: boolean;
        };
        /** DecisionResponse */
        DecisionResponse: {
            /**
             * Allowed
             * @default false
             */
            allowed: boolean;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Matched */
            matched?: string[];
            /** Failed */
            failed?: string[];
            /** Obligations */
            obligations?: string[];
            /**
             * Policy Id
             * @default
             */
            policy_id: string;
            /**
             * Evaluated At
             * @default
             */
            evaluated_at: string;
            /** Evaluated Conditions */
            evaluated_conditions?: {
                [key: string]: unknown;
            }[];
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            } | null;
        };
        /** EvidenceLogResponse */
        EvidenceLogResponse: {
            /** Entries */
            entries: components["schemas"]["EvidenceModel"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Verified */
            verified: boolean;
        };
        /** EvidenceModel */
        EvidenceModel: {
            /**
             * Evidence Id
             * @default
             */
            evidence_id: string;
            /**
             * Version
             * @default
             */
            version: string;
            /**
             * Timestamp
             * @default
             */
            timestamp: string;
            /** Actor */
            actor?: {
                [key: string]: unknown;
            };
            /**
             * Resource Id
             * @default
             */
            resource_id: string;
            /**
             * Resource Hash
             * @default
             */
            resource_hash: string;
            /** Policy */
            policy?: {
                [key: string]: unknown;
            };
            /**
             * Operation
             * @default
             */
            operation: string;
            /**
             * Result
             * @default
             */
            result: string;
            /** Policy Evaluation */
            policy_evaluation?: {
                [key: string]: unknown;
            };
            /**
             * Signature
             * @default
             */
            signature: string;
            /**
             * Public Key Id
             * @default
             */
            public_key_id: string;
            /**
             * Signing Algorithm
             * @default
             */
            signing_algorithm: string;
            /**
             * Parent Hash
             * @default
             */
            parent_hash: string;
            /**
             * Position
             * @default 0
             */
            position: number;
            /** Metadata */
            metadata?: {
                [key: string]: string;
            };
        };
        /** ExplainResponse */
        ExplainResponse: {
            /**
             * Allowed
             * @default false
             */
            allowed: boolean;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Services */
            services: {
                [key: string]: string;
            };
            /** Version */
            version: string;
        };
        /** KeyGenerateRequest */
        KeyGenerateRequest: {
            /** Algorithm */
            algorithm?: string | null;
            /**
             * Type
             * @default encryption
             */
            type: string;
            /**
             * Organization
             * @default
             */
            organization: string;
            /**
             * Owner
             * @default
             */
            owner: string;
            /** Metadata */
            metadata?: {
                [key: string]: string;
            };
        };
        /** KeyInfoModel */
        KeyInfoModel: {
            /**
             * Key Id
             * @default
             */
            key_id: string;
            /**
             * Algorithm
             * @default
             */
            algorithm: string;
            /**
             * Type
             * @default
             */
            type: string;
            /**
             * Public Key
             * @default
             */
            public_key: string;
            /**
             * Status
             * @default
             */
            status: string;
            /**
             * Created At
             * @default
             */
            created_at: string;
            /**
             * Expires At
             * @default
             */
            expires_at: string;
            /**
             * Rotated At
             * @default
             */
            rotated_at: string;
            /**
             * Revoked At
             * @default
             */
            revoked_at: string;
            /**
             * Organization
             * @default
             */
            organization: string;
            /**
             * Owner
             * @default
             */
            owner: string;
        };
        /** KeyListResponse */
        KeyListResponse: {
            /** Keys */
            keys: components["schemas"]["KeyInfoModel"][];
        };
        /** KeyResponse */
        KeyResponse: {
            /** Key Id */
            key_id: string;
            /** Public Key */
            public_key: string;
            /** Algorithm */
            algorithm: string;
            /** Type */
            type: string;
            /** Status */
            status: string;
            /** Created At */
            created_at: string;
        };
        /** PolicyEvaluateRequest */
        PolicyEvaluateRequest: {
            /** Policy */
            policy: {
                [key: string]: unknown;
            };
            /** Identity */
            identity: {
                [key: string]: unknown;
            };
            /** Context */
            context?: {
                [key: string]: unknown;
            } | null;
        };
        /** PolicyEvaluationResponse */
        PolicyEvaluationResponse: {
            /**
             * Decision
             * @default denied
             */
            decision: string;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Evaluated Conditions */
            evaluated_conditions?: {
                [key: string]: unknown;
            }[];
        };
        /** ProtectRequest */
        ProtectRequest: {
            /**
             * Data
             * @description base64-encoded plaintext
             */
            data: string;
            /** Policy */
            policy: {
                [key: string]: unknown;
            };
            /** Algorithm */
            algorithm?: string | null;
            /** Key Id */
            key_id?: string | null;
            /**
             * Resource Id
             * @default
             */
            resource_id: string;
            /** Actor */
            actor?: {
                [key: string]: unknown;
            } | null;
        };
        /** ProtectResponse */
        ProtectResponse: {
            /**
             * Protected Data
             * @description base64-encoded envelope
             */
            protected_data: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            evidence: components["schemas"]["EvidenceModel"];
        };
        /** SealRequest */
        SealRequest: {
            /**
             * Data
             * @description base64-encoded data to sign
             */
            data: string;
            /**
             * Key Id
             * @default
             */
            key_id: string;
            /**
             * Algorithm
             * @default
             */
            algorithm: string;
        };
        /** SealResponse */
        SealResponse: {
            /**
             * Data Hash
             * @default
             */
            data_hash: string;
            /**
             * Signature
             * @default
             */
            signature: string;
            /**
             * Algorithm
             * @default
             */
            algorithm: string;
            /**
             * Key Id
             * @default
             */
            key_id: string;
            /**
             * Sealed At
             * @default
             */
            sealed_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifyRequest */
        VerifyRequest: {
            evidence: components["schemas"]["EvidenceModel"];
            /**
             * Reevaluate
             * @default true
             */
            reevaluate: boolean;
        };
        /** VerifyResponse */
        VerifyResponse: {
            /** Verified */
            verified: boolean;
            /** Signature Valid */
            signature_valid: boolean;
            /** Chain Valid */
            chain_valid: boolean;
            /** Policy Compliant */
            policy_compliant: boolean;
            /**
             * Detail
             * @default
             */
            detail: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    protect_api_v1_protect_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProtectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProtectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    access_api_v1_access_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccessRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_api_v1_verify_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evidence_log_api_v1_evidence_log_get: {
        parameters: {
            query?: {
                resource_id?: string;
                actor_id?: string;
                page?: number;
                page_size?: number;
            };
            header?: {
                "x-api-key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceLogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_keys_api_v1_keys_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_api_v1_keys_generate_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeyGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_key_api_v1_keys__key_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
                authorization?: string | null;
            };
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rotate_api_v1_keys_rotate__key_id__post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
                authorization?: string | null;
            };
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_v1_keys_revoke__key_id__post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
                authorization?: string | null;
            };
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_api_v1_policy_evaluate_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyEvaluateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyEvaluationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_api_v1_check_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_api_v1_explain_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    seal_api_v1_seal_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SealRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SealResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_evidence_api_v1_evidence_export_get: {
        parameters: {
            query?: {
                resource_id?: string;
                actor_id?: string;
                start_time?: string;
                end_time?: string;
                format?: string;
            };
            header?: {
                "x-api-key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compliance_report_api_v1_compliance_report_get: {
        parameters: {
            query?: {
                framework?: string;
                resource_id?: string;
                actor_id?: string;
                start_time?: string;
                end_time?: string;
            };
            header?: {
                "x-api-key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
